---
- name: Add Docker repo.
  yum_repository:
    name: docker 
    description: docker repo
    baseurl: 
      - https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker package and dependencies
  yum:
    name: ["docker-ce", "docker-ce-cli", "containerd.io"]
    state: present

- name: Start Docker
  service:
    name: docker
    state: started
