---
- name: Add Docker repo.
  command: >
    sudo yum-config-manager 
    --add-repo 
    https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo 

- name: Install Docker package and dependencies
  yum:
    name: ["docker-ce", "docker-ce-cli", "containerd.io"]
    state: present

- name: Start Docker
  service:
    name: docker
    state: started
