---
- name: Verify if the cluster is already up
  command: docker node ls
  register: swarm_status
  ignore_errors: true
  
- name: initialize swarm
  command: >
    docker swarm init
    --advertise-addr={{ ansible_facts['enp3s0']['ipv4'] }}:2377
  when: swarm_status.rc != 0
  notify: output the tokens

- name: get Manager token
  command: docker swarm join-token manager
  register: manager_token

- name: get worker token
  command: docker swarm join-token worker
  register: worker_token



